version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - development
  - beta-releases
  - Release-Candidates
skip_tags: true
build_script:
- sh: mkdir bin ; cd bin ; meson .. ; ninja

test_script:
- sh: ninja test
deploy: off
on_finish:
- sh: cd ../.. ; rm -rf DiscordBot/
